FROM python:3.12-bullseye

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PYTHONIOENCODING=utf-8 \
    # pip
    PIP_NO_CACHE_DIR=1 \
    PIP_DISABLE_PIP_VERSION_CHECK=1 \
    PIP_DEFAULT_TIMEOUT=100 \
    PIP_ROOT_USER_ACTION=ignore \
    # uv
    UV_CACHE_DIR='/opt/uv-cache/' \
    UV_SYSTEM_PYTHON=1 \
    # app
    PROMETHEUS_MULTIPROC_DIR=/tmp/prometheus_multiproc_dir

SHELL ["/bin/bash", "-eo", "pipefail", "-c"]

RUN apt-get update && \
    apt-get install -y gcc libpq-dev curl ca-certificates && \
    rm -rf /var/cache/apt/*

ADD https://astral.sh/uv/0.3.2/install.sh /uv-installer.sh
RUN sh /uv-installer.sh && rm /uv-installer.sh
ENV PATH="/root/.cargo/bin/:$PATH"

COPY pyproject.toml /src/

WORKDIR /src

RUN --mount=type=cache,target=/root/.cache/uv \
    uv pip install -r pyproject.toml

COPY . .

RUN uv pip install -e .

RUN useradd -m -d /src -s /bin/bash app \
    && chown -R app:app /src/* && chown -R app:app /src \
    && chmod +x entrypoints/* \
    && rm -rf /tmp/prometheus_multiproc_dir && mkdir -p /tmp/prometheus_multiproc_dir \
    && chown -R app:app /tmp/prometheus_multiproc_dir

USER app